### PR TITLE
MERGE DEVELOP INTO MASTER!

### PR DESCRIPTION
**Pull request by smileycreations15**

### CODE REVIEW

**Comment by smileycreations15** [comment]
@AfterNetwork Please approve this pull request at https://github.com/AfterNetwork-SmileyCreations-Projects/Smile.js/pull/9/files and click <kbd>Review Changes</kbd>.

**Comment by AfterNetwork** [comment]
what the

**Comment by smileycreations15** [comment]
@AfterNetwork Your comment has been minimized as it partially violated the code of conduct.

**Comment by AfterNetwork** [comment]
It seems like your files are not up to the standards:
https://app.codacy.com/app/afterschooln123/Smile.js/pullRequest?prid=3726471

**Comment by smileycreations15** [comment]
@AfterNetwork Check again.

**Comment by AfterNetwork** [comment]
Just, no. Fix the other errors at: https://app.codacy.com/app/afterschooln123/Smile.js/pullRequest?prid=3726471

**Comment by smileycreations15** [comment]
@AfterNetwork These errors are normal and do not affect quality whatsoever.

**Comment by AfterNetwork** [comment]
FINE

**Comment by smileycreations15** [comment]
> STOP IT

@AfterNetwork What did I do?

**Pull request merged**
